Software Technologies July '17 Retake exam 05.09/0509/C#/AnimeList/Models/Anime.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace AnimeList.Models
{
    public class Anime
    {
        public int Id { get; set; }

        [Required]
        public int Rating { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Watched { get; set; }
    }
}

Software Technologies July '17 Retake exam 05.09/0509/C#/AnimeList/Models/AnimeListDbContext.cs
using System.Data.Entity;

namespace AnimeList.Models
{
    public class AnimeListDbContext : DbContext
    {
        public virtual IDbSet<Anime> Animes { get; set; }

        public AnimeListDbContext() : base("AnimeList")
        {
        }
    }
}

Software Technologies July '17 Retake exam 05.09/0509/C#/AnimeList/Controllers/AnimeController.cs
using System.Linq;
using System.Web.Mvc;
using AnimeList.Models;

namespace AnimeList.Controllers
{
    [ValidateInput(false)]
    public class AnimeController : Controller
    {
        [HttpGet]
        [Route("")]
        public ActionResult Index()
        {
            using(var db=new AnimeListDbContext())
            {
                var vm = db.Animes.ToList();
                return View(vm);
            }
        }

        [HttpGet]
        [Route("create")]
        public ActionResult Create() => View();

        [HttpPost]
        [Route("create")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Anime anime)
        {
            using(var db=new AnimeListDbContext())
            {
                db.Animes.Add(anime);
                db.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("delete/{id}")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }

            using (var db = new AnimeListDbContext())
            {
                var vm = db.Animes.Single(x => x.Id == id);
                return View(vm);
            }
        }

        [HttpPost]
        [Route("delete/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int? id, Anime animeModel)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }

            using(var db=new AnimeListDbContext())
            {
                var anime = db.Animes.Single(x => x.Id == id);
                db.Animes.Remove(anime);
                db.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Software Technologies July '17 Retake exam 05.09/0509/C#/AnimeList/Views/Anime/Create.cshtml
@model AnimeList.Models.Anime

@{
    ViewBag.Title = "Add New Anime";
}

<h1>Add New Anime</h1>

<section>
    @using (Html.BeginForm("Create", "Anime", FormMethod.Post, new { onsubmit = "checkValue()" }))
    {
        @Html.AntiForgeryToken()
    
        <div>
            <label for="rating">Rating</label>
            <input type="text" id="rating" name="rating" value="0">
            <label for="name">Name</label>
            <input type="text" id="name" name="name">
            <label for="description">Description</label>
            <input type="text" id="description" name="description" value="...">
            <label for="watched">Watched</label>
            <input type="checkbox" id="watched" value="not watched" name="watched" onclick="switchValue()">
            <label for="watched" id="watched-label"></label>
            <button type="submit" class="accept">Create</button>
            <button type="button" class="cancel" onclick="location.href='/';return false;">Cancel</button>
        </div>
    }
</section>

<script>
    function switchValue() {
        document.getElementById("watched").value =
            document.getElementById("watched").value === "watched" ? "not watched" : "watched";
    }

    function checkValue() {
        document.getElementById("watched").checked = true;
    }

    (function checkBox() {
        let checkbox = document.getElementById("watched");
        checkbox.checked = checkbox.value !== "not watched";
    })();
</script>

Software Technologies July '17 Retake exam 05.09/0509/C#/AnimeList/Views/Anime/Delete.cshtml
@model AnimeList.Models.Anime

@{
    ViewBag.Title = "Delete Anime";
}

<h1>Delete Anime</h1>

<section>
        @using (Html.BeginForm("Delete", "Anime", FormMethod.Post, new { onsubmit = "checkValue()" }))
        {
            @Html.AntiForgeryToken()

            <div>
                <label for="rating">Rating</label>
                <input type="text" id="rating" value="@Model.Rating" name="rating" disabled>
                <label for="name">Name</label>
                <input type="text" id="name" value="@Model.Name" name="name" disabled>
                <label for="description">Description</label>
                <input type="text" id="description" value="@Model.Description" name="description" disabled>
                <label for="watched">Watched</label>
                <input type="checkbox" id="watched" value="@Model.Watched" name="watched" disabled>
                <label for="watched" id="watched-label"></label>
                <button type="submit" class="accept">Delete</button>
                <button type="button" class="cancel" onclick="location.href='/';return false;">Cancel</button>
            </div>
        }
</section>

<script>
    function checkValue() {
        document.getElementById("watched").checked = true;
        document.getElementById("rating").disabled = false;
        document.getElementById("name").disabled = false;
        document.getElementById("description").disabled = false;
        document.getElementById("watched").disabled = false;
    }

    (function checkBox() {
        let checkbox = document.getElementById("watched");
        checkbox.checked = checkbox.value !== "not watched";
    })();
</script>

Software Technologies July '17 Retake exam 05.09/0509/C#/AnimeList/Views/Anime/Index.cshtml
@model List<AnimeList.Models.Anime>

@{
    ViewBag.Title = "Anime List";
}


<h1>Anime List</h1>

<section>
    <div>
        <table>
            <tr>
                <th>Rating</th>
                <th>Name</th>
                <th>Description</th>
                <th>Watched</th>
                <th>Actions</th>
            </tr>
            @foreach (var anime in Model.ToList())
            {
            <tr>
                <td>@anime.Rating</td>
                <td>@anime.Name</td>
                <td>@anime.Description</td>
                <td>
                    <input class="checkbox" type="checkbox" value="@anime.Watched" onclick="preventEvent(event)" name="@anime.Name"/>
                    <label for="@anime.Name"></label>
                </td>
                <td>
                    <button class="delete" onclick="location.href='/delete/@anime.Id';return false;">Delete</button>
                </td>
            </tr>
            }
        </table>
    </div>
</section>

<div>
    <button class="add-new" onclick="location.href='/create';return false;">+</button>
</div>

<script>
    function preventEvent(ev) {
        ev.preventDefault();
    }
    (function checkBox() {
        let checkboxes = document.getElementsByClassName("checkbox");

        for (let i = 0; i < checkboxes.length; i++) {
            if (checkboxes[i].value === "watched") {
                checkboxes[i].checked = true;
            }
        }
    })();
</script>

Software Technologies July '17 Retake exam 05.09/0509/C#/AnimeList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Anime List</title>
	@Styles.Render("~/Content/style.css")
</head>
<body>
	@RenderBody()
</body>
</html>